name: tribecarexercise
recipe: lamp
config:
  webroot: .
  php: '8.1'
proxy:
  appserver:
    - tribecarexercise.lndo.site:7880
    - "*.tribecarexercise.lndo.site:7880"
  phpmyadmin:
    - "phpmyadmin.tribecarexercise.lndo.site:9883"
tooling:
  phpunit:
    service: appserver
    description: Runs phpunit command
    cmd: ./vendor/bin/phpunit
    user: root
  cake:
    service: appserver
    description: Runs CakePHP command
    cmd: /app/bin/cake
services:
  appserver:
    build_as_root:
      - apt update && apt full-upgrade -y && apt autoremove -y
      - apt install nano
    run_as_root:
      - composer install -o
      - bin/cake migrations migrate
    ports:
      - "7880:80"
  database:
    type: mysql:8.0
    creds:
      user: landoroot
      password: password
      database: tribecarexercise
  database_test:
    type: mysql:8.0
    creds:
      user: landoroot
      password: password
      database: tribecarexercise_test
  phpmyadmin:
    type: phpmyadmin
    ports:
      - "9883:80"
